### ISSUE TITLE
Is Zero, Is Equal functions

### ISSUE THREAD

**Issue by cxong** [ferreiradaselva/mathc#16]
It would be handy to have functions that check if the vector/quaternion is equal to some other vector/quaternion, especially zero.

For the equals functions, epsilon needs to be provided. For zero, using machine epsilon is ok.

**Comment by felselva** [comment]
Done. Added functions to test 2D vectors, 3D vectors and quaternions in https://github.com/ferreiradaselva/mathc/commit/4758ea273d035198814352b0a3cd72c3f4a06186.
