### ISSUE TITLE
Compiler warnings for missing field initializers

### ISSUE THREAD

**Issue by cxong** [ferreiradaselva/mathc#22]
This code produces a warning when gcc/clang have warnings turned to full, or if `-Wmissing-field-initializers` is defined:

    struct vec b_minus_a = {0};

Although this is valid C99 initialisation, should mathc aim to produce no compiler warnings? If so this needs to be replaced with say

    struct vec a = {0, 0, 0, 0};
    // or
    struct vec a = vector2_zero();

**Comment by felselva** [comment]
I will make the update (had no idea of the existence of `-Wmissing-field-initializers`).

**Comment by felselva** [comment]
Fixed with https://github.com/ferreiradaselva/mathc/commit/0970ef008d87a0931effeb85a0c3ebe4b7033d86.

**Comment by cxong** [comment]
You can have travis check such errors by adding warning flags to `run_tests.h` (`-Wall -Werror`)
