### ISSUE TITLE
Use macros to define similar functions

### ISSUE THREAD

**Issue by cxong** [ferreiradaselva/mathc#23]
The functions for different vector sizes are very similar, but they are repeated in the code. This means mistakes are easy to make.
I suggest using macros to define these functions, so you write the code once and use macros to define the other vector versions.

Here's some sample code for doing this kind of thing:

	#include <stdio.h>

	#define CAT(x, y) x##y
	#define MAKE_FUNC(_num) \
	void CAT(foo, _num)(void) { printf("func %d\n", _num); }

	MAKE_FUNC(2)
	MAKE_FUNC(3)

	int main(void) {
		foo2();
		foo3();
		return 0;
	}

**Comment by RandyGaul** [comment]
Don't think this is a good idea. Yes, macros can remove code duplication here, but at the cost of code readability. A very common use-case for math libraries is to step into the functions to manually verify an understanding of what the math library is doing. These macros completely ruin modern debugger stepping. It is much more important to explicitly write down all of the functions for simplicity of reading, than to remove code duplication during implementation.

**Comment by ghost** [comment]
We rater make sure by writing proper tests and/or use formal methods based on static analysis to make sure these are formally correct. By implementing the same function across multiple types, you are taking away any possibility to tweak the individual functions. Of course you may argue that display functions don't need special casing, but considering how obviously bad the c preprocessor is at these things, I'd advise to just leave it alone.
I'd rather even go and suggest an internal printer function that is called from a - constant-bound, therefore compiler-unrollable - loop.

**Comment by felselva** [comment]
I agree that the macros make the code less readable (it was one of the reasons I started this library - some out there heavily uses macros).

**Comment by cxong** [comment]
Will close this due to concerns about code readability. The real problem is that functions were inconsistent, but that can be solved in other ways, e.g. more tests.
