### ISSUE TITLE
Add vectors with integer fields

### ISSUE THREAD

**Issue by felselva** [ferreiradaselva/mathc#3]
Vectors with integer fields are less used, but are still usable. They won't have as many functions as the vectors with float fields, but they will have minimally the basic math operation functions.

**Comment by satubhaRANA** [comment]
Xvy

**Comment by felselva** [comment]
What does that mean?

**Comment by RandyGaul** [comment]
spambot

**Comment by cxong** [comment]
I've built a 2D integer vector module for C-Dogs SDL, you can take a look at the interface here: https://github.com/cxong/cdogs-sdl/blob/master/src/cdogs/vector.h
If you're interested, I'll be happy to adapt this code into this project, with your choice of license, naming conventions etc.

**Comment by felselva** [comment]
I'm still in doubt if I will add vectors with integer (so far, float points are doing the job). Thanks, anyway!

**Comment by felselva** [comment]
I'm closing, because `float` vectors has proven to be good enough, in my opinion.
