### ISSUE TITLE
About clamp feature

### ISSUE THREAD

**Issue by heitaoflower** [ferreiradaselva/mathc#30]
Hi, I just wondering if you can add a feature of clamp, both of clampi and clampf

something like that,
#define CLAMP(value, min, max) (min < max           \
  ? (value < min ? min : value > max ? max : value) \
  : (value < max ? max : value > min ? min : value) \
  )

mfloat_t clampf(float value, float min, float max);
int clampf(int value, int min, int max);

I am will vrey glad to see u do that.

**Comment by felselva** [comment]
Will send a patch soon.
