### ISSUE TITLE
add CI tests

### ISSUE THREAD

**Issue by barrotsteindev** [ferreiradaselva/mathc#4]
proposal to add CI/CD tests, for example using travis ci to compile the code and run the test file.
I have no problem to start working on this if it is found to be needed.

**Comment by felselva** [comment]
Nice addition. I don't know much on how to use Travis-CI, but seems simple enough.

**Comment by barrotsteindev** [comment]
now that the PR #5  is merged, you need to go to [travis-ci](https://travis-ci.org/), login using GitHub and enable tests for this repository. After that every push will trigger an automatic build on travis-ci.

**Comment by barrotsteindev** [comment]
P.S. the current build result can be added to the readme file, and be shown on github, there is a simple tutorial on ther travis-ci site. Feel free to ask me any question if you get into trouble

**Comment by felselva** [comment]
Thanks for the PR!
