### ISSUE TITLE
Should 2D vectors be removed and keep only 3D vectors?

### ISSUE THREAD

**Issue by felselva** [ferreiradaselva/mathc#7]
2D vectors can be simply represented as 3D vectors with `z = 0.0f`. However, matrices only works with 3D vectors, and it's inconvenient to convert from 2D to 3D just to use with matrices, as in this case:

```c
cvector2 position = to_vector2(0.0f, 0.0f);
m = matrix_translation(to_vector3(position.x, position.y, 0.0f));
```

Working only with 3D vectors would make things simpler:
```c
cvector3 position = to_vector3(0.0f, 0.0f, 0.0f);
m = matrix_translation(position);
```

The `z` component of 3D vectors are also useful in 2D games for z-ordering.

Functions like `vector2_dot` and `vector2_angle` will still exist, but they will only operate on the `x` and `y` components of a 3D vector:

```c
float vector2_dot(cvector3 v);
float vector2_angle(cvector3 v);
```

To remove 2D vectors, react with :+1:.

To keep 2D vectors, react with :-1:.

**Comment by RandyGaul** [comment]
just use the vector3 type, but make a bunch of vector2 functions, like your example:

    float vector2_dot(cvector3 v);
    float vector2_angle(cvector3 v);

**Comment by RandyGaul** [comment]
Actually a lot of math libs use 4 component vectors as the data type, so they can be easily compatible with SIMD intrinsics. And then use the 4 component data type for both 2d and 3D vector APIs. The API can have a specific dimensions that doesn’t necessarily match one to one with the data’s number of floating point components.
