### ISSUE TITLE
matrix_to_array functions

### ISSUE THREAD

**Issue by nobledemon** [ferreiradaselva/mathc#8]
This is more of a (possibly) dumb question rather than an issue.

Readme.md says:

> If you want to modify on GPU-side, you can use the functions matrix_to_array() or pmatrix_to_array() to push the matrix to an array with 16 float elements. 

Wouldn't it be possible to just cast the struct to float* since it's a pod struct? Is there a benefit to doing this way?

**Comment by felselva** [comment]
As far as I know, you can. I just didn't mention that, because I don't know if every compiler guarantee alignment.

From [this stackoverflow](https://stackoverflow.com/a/5524587) answer:
> If all members a guaranteed to be of type int you can use a pointer to int and increment it:
> ```c
> int *value = &(values.v_move);
> int *quantity = &(quantities.qtt_move);
> int i;
> average = 0;
> // although it should work, a good practice many times IMHO is to add a null as the last member in struct and change the condition to quantity[i] != null.
> for (i = 0; i < sizeof(quantities) / sizeof(*quantity); i++)
>     average += values[i] * quantity[i];
> ```
